[phases.setup]
nixPkgs = ["...", "nodejs_20", "chromium"]

[phases.install]
cmds = ["cd api && npm install"]

[phases.build]
cmds = ["cd api && npm run build"]

[start]
cmd = "cd api && node index.js"
