[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd api && node index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "3001"
FRONTEND_URL = "https://playwithui.vercel.app"
